//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//added by samsuri (CR#57258)  on 10 Jan 2024
namespace TourlistDataLayer.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class tobtab_add_branches_updated
    {
        [Key]
        public Guid tobtab_add_branches_upd_idx { get; set; }

        [Required]
        public Guid stub_ref { get; set; }

        public Nullable<Int16> Is_change_address { get; set; }

        //new info
        [StringLength(400)]
        public string new_branch_addr_1 { get; set; }

        [StringLength(400)]
        public string new_branch_addr_2 { get; set; }

        [StringLength(400)]
        public string new_branch_addr_3 { get; set; }

        [StringLength(60)]
        public string new_branch_postcode { get; set; }

        public Guid? new_branch_city { get; set; }

        public Guid? new_branch_state { get; set; }

        //old info
        [StringLength(400)]
        public string old_branch_addr_1 { get; set; }

        [StringLength(400)]
        public string old_branch_addr_2 { get; set; }

        [StringLength(400)]
        public string old_branch_addr_3 { get; set; }

        [StringLength(60)]
        public string old_branch_postcode { get; set; }

        public Guid? old_branch_city { get; set; }

        public Guid? old_branch_state { get; set; }

        public Byte? active_status { get; set; } = 1; //tinyint in sql = Byte in C#

        public DateTime created_at { get; set; }
        public Guid created_by { get; set; }
        public DateTime modified_at { get; set; }
        public Guid modified_by { get; set; }

        [Column(TypeName = "timestamp")]
        [MaxLength(8)]
        [Timestamp]
        public byte[] trx_dt { get; set; }
    }
}
